@trackerUrl = http://localhost:5000

### get peers
GET {{trackerUrl}}/peers


### get peers count
GET {{trackerUrl}}/peers_count


### Upload Torrent File
POST http://localhost:10000/uploadTorrent
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="torrentFile"; filename="pingplotter_install.exe.torrent"
Content-Type: application/x-bittorrent

< ./Torrent_File/seqlock.torrent
--boundary--


### Download Torrent File

POST http://localhost:10000/createTorrent
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="seqlock.h"
Content-Type: application/x-bittorrent

< ./some_torrent/seqlock.h
--boundary--


### Upload File
POST http://localhost:10001/uploadFile
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="seqlock.h"
Content-Type: application/x-bittorrent

< ./some_torrent/seqlock.h
--boundary--

### Ping
GET http://localhost:3000/ping

### Get Peer List
GET http://localhost:5000/peers?fileName=seqlock.h

### Get Peer List
GET http://localhost:10001/peers?trackerUrl=http://localhost:5000&fileName=music.mp3

### Get File List
GET http://localhost:10000/files

### Get File List
GET http://localhost:10000/downloadedFiles

### Get Peer List from tracker
GET http://localhost:5000/peers?fileName=heavy.iso

### Download File
POST http://localhost:30001/download
Content-Type: application/json

{
    "trackerUrl": "http://localhost:5000",
    "fileName": "music.mp3"
}


### Download File
POST http://localhost:10001/download
Content-Type: application/json

{
    "trackerUrl": "http://localhost:5000",
    "fileName": "Assignment 1.pdf"
}


### Download File
POST http://localhost:10000/download
Content-Type: application/json

{
    "trackerUrl": "http://localhost:5000",
    "fileName": "test.http"
}

### Download File
POST http://localhost:10000/download
Content-Type: application/json

{
    "trackerUrl": "http://localhost:5000",
    "fileName": "no-image.png"
}


### Hash test
GET http://localhost:5000/hash?file_name=music.mp3